spring.application.name=asist-viajes-project


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



gemini.api-key=${GEMINI_API_KEY}
gemini.model=gemini-2.5-flash
gemini.base-url=https://generativelanguage.googleapis.com/v1beta


security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.expiration-minutes=60